Import dependencies

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import joblib
import os
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

In [34]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

Data Pre-processing

In [35]:
#Import the dataset
real=pd.read_csv("D:\\TruthLens\\Data\\True.csv")
fake=pd.read_csv("D:\\TruthLens\\Data\\Fake.csv")

In [36]:
#Create labels
real["label"] = 0
fake["label"] = 1

In [37]:
real.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0

In [38]:
fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1

In [39]:
#Combining the datasets
df=pd.concat([real,fake],ignore_index=True)

In [40]:
df.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0

In [41]:
#Shuffle the data
df = df.sample(frac=1, random_state=40).reset_index(drop=True)

In [42]:
df.head()

,title,text,subject,date,label
0,FBI UNDERCOVER Informant On Hillary’s 2010 Sal...,The FBI informant who went undercover to look ...,Government News,"Nov 17, 2017",1
1,BREAKING #BetsyDeVos CONFIRMED: DEMOCRATS SEET...,Watch History in the making!@VP breaks the TIE...,politics,"Feb 7, 2017",1
2,"U.S. plans to admit maximum 45,000 refugees in...",WASHINGTON (Reuters) - The Trump administratio...,politicsNews,"September 27, 2017",0
3,Senate Republican tax chief wants dividend ded...,WASHINGTON (Reuters) - The U.S. Senate’s top R...,politicsNews,"September 19, 2017",0
4,Victims Of Terrorist Attack Question Lack Of ...,Minnesota s governor did something the current...,News,"August 8, 2017",1

In [43]:
df.shape

(44898, 5)

In [44]:
df.columns

Index(['title', 'text', 'subject', 'date', 'label'], dtype='str')

In [45]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [46]:
df.tail()

,title,text,subject,date,label
44893,UK PM May says she was unaware of allegations ...,LONDON (Reuters) - British Prime Minister Ther...,worldnews,"December 22, 2017",0
44894,Oregon Won’t Prosecute Baby’s Abuser Because ...,An anguished Oregon couple took to social medi...,News,"May 22, 2016",1
44895,Lebanon FM says Hariri crisis an attempt to cr...,BEIRUT (Reuters) - Lebanon s Foreign Minister ...,worldnews,"November 17, 2017",0
44896,JUST IN: Flynn to Plead Guilty to Lying to the...,The broader story in this entire Russia witch ...,politics,"Dec 1, 2017",1
44897,"Israel rejects U.N. vote, thanks Trump for sta...",JERUSALEM (Reuters) - Israel rejected a U.N. v...,worldnews,"December 21, 2017",0

In [47]:
df["label"].value_counts()

label
1    23481
0    21417
Name: count, dtype: int64

In [48]:
#Combining the title and text columns into a single content column
df['content']=df['title']+' '+df['text']

In [49]:
print(df['content'])

0        FBI UNDERCOVER Informant On Hillary’s 2010 Sal...
1        BREAKING #BetsyDeVos CONFIRMED: DEMOCRATS SEET...
2        U.S. plans to admit maximum 45,000 refugees in...
3        Senate Republican tax chief wants dividend ded...
4         Victims Of Terrorist Attack Question Lack Of ...
                               ...
44893    UK PM May says she was unaware of allegations ...
44894     Oregon Won’t Prosecute Baby’s Abuser Because ...
44895    Lebanon FM says Hariri crisis an attempt to cr...
44896    JUST IN: Flynn to Plead Guilty to Lying to the...
44897    Israel rejects U.N. vote, thanks Trump for sta...
Name: content, Length: 44898, dtype: str

In [50]:
df.to_csv("D:\\TruthLens\\Data\\combined_data.csv", index=False)

Stemming

In [51]:
#Loading PorterStemming function
port_stem=PorterStemmer()

In [54]:
#Loading stopwords
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [55]:
#Creating a function for stemming the content
def stemming(content):
    stemmed_content=re.sub('[^a-zA-Z]',' ',content)
    stemmed_content=stemmed_content.lower()
    stemmed_content=stemmed_content.split()
    stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stop_words]
    stemmed_content=' '.join(stemmed_content)
    return stemmed_content

In [56]:
#Applying the stemming function to the content column
df['content']=df['content'].apply(stemming)

In [57]:
print(df['content'])

0        fbi undercov inform hillari sale uranium ident...
1        break betsydevo confirm democrat seeth champio...
2        u plan admit maximum refuge next fiscal year w...
3        senat republican tax chief want dividend deduc...
4        victim terrorist attack question lack presiden...
                               ...
44893    uk pm may say unawar alleg sack deputi london ...
44894    oregon prosecut babi abus young testifi anguis...
44895    lebanon fm say hariri crisi attempt creat regi...
44896    flynn plead guilti lie fbi broader stori entir...
44897    israel reject u n vote thank trump stanc jerus...
Name: content, Length: 44898, dtype: str

In [58]:
#Separating the data & label
X=df['content'].values
Y=df['label'].values

In [59]:
print(X)

<StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'fbi undercov inform hillari sale uranium identifi fbi inform went undercov look hillari clinton role obama administr era uranium compani identifi yesterday exclus reuter william campbel russian lobbyist inform accord reuter testifi congression committe sale uranium one russian back compani bought uranium firm mine u campbel gave inform fbi saw undercov inform work justic depart undercov sever year document relat uranium one polit influenc exist william campbellcongression committe previous tri interview campbel undercov roughli five year work get inform russia effort grow atom energi busi u depart justic spokeswoman sarah isgur flore told hill deal reach late octob clear inform talk congress first time almost eight year first went undercov two hous chairmen also announc probe late octob dig new report russian effort influenc uranium one nuclear purchas gave russia control roughli percent america uranium clinton serv secretari state russia rout million dollar clinton foundat former presid bill clinton collect hundr thousand dollar russian speak fee part russian effort influenc u govern approv deal hill report previou report gag order lift session lawyer fbi inform client know russian say briberi clinton video campbel attorney victoria toens said fox busi former attorney gener obama administr reason client abl tell russian talk time briberi payment made lawyer fbi inform gag order prevent go congress spoke come clinton russia uranium stori fox busi report inform feder bureau investig fbi gag order prevent testifi unit state congress russian nuclear offici involv fraudul deal uranium one deal approv former attorney gener loretta lynch block inform testifi last year threaten crimin action interview fox busi lou dobb victoria toens attorney repres fbi inform said never heard crimin penalti breach non disclosur agreement nda unconstitut invalid prohibit client give inform legislatur execut cannot say peopl hey give inform anoth bodi govern toens said key point republican leadership block investig benghazi russia uranium scandal involv clinton nda gag order unconstitut toens say type gag order crimin penalti say never heard type gag order victoria toens one best lawyer dc get bottom one way anoth plot thicken one read daili caller',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'break betsydevo confirm democrat seeth champion inner citi educ trump new educ secretari watch histori make vp break tie confirm betsi devo sec educ magap twitter com hon mfofyc cc christichat februari devo polar figur educ circl strong support school choic charter school critic said advoc like push school choic littl regard qualiti option parent give famili opportun make educ relat decis behalf children appar scari proposit radic teacher union fox news trish regan say democrat opposit betsi devo dem oppos devo bigtim school choic threaten union give student famili abil demand account imagin trish regan trish regan februari advoc believ strongli parent abl decid kid go school kid trap fail school critic say choic advoc ignor need qualiti option say charter siphon money away tradit public school point data show charter school perform better case perform wors counterpart devo husband dick led fail petit drive institut voucher system michigan would allow parent use public money send children privat school state constitut prohibit use public fund voter overwhelmingli reject propos similar plan centerpiec trump educ plan want spend billion feder fund spent thing expect state kick even provid pay privat school tuition everi high poverti child countri detroit free presscrybabi democrat comedian us senat al franken happi devo confirm take control live live children never popular democrat parti circl shame gop vote confirm one major donor instead look children full statement http co ibyt sqac sen al franken senfranken februari',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'u plan admit maximum refuge next fiscal year washington reuter trump administr plan admit refuge unit state fiscal year start oct former u offici said tuesday ceil would keep admiss lowest level decad white hous settl figur contenti debat offici want lower ceil want higher one said former offici spoke condit anonym one side debat offici tend look issu domest polit prism given presid donald trump focu curb immigr u presidenti campaign foreign polici expert argu take refuge unit state vital ensur nation keep border open plan set cap earlier report wall street journal newspap former offici favor higher number said decis undermin u abil persuad nation jordan turkey lebanon accept huge flow syrian refuge keep admit well convinc donor nation keep financi contribut refuge stand play role cut humanitarian assist halv refuge admiss said former offici two travel ban execut order trump direct unit state accept maximum refuge perman resettl fiscal year end sept less half presid barack obama author part court challeng order unit state ultim accept refuge current fiscal year accord state depart data unit state took refuge august unit state accept fiscal would lowest level admit sinc fiscal took accord state depart data state depart spokesman declin comment figur say secretari state rex tillerson act secretari homeland secur elain duke would consult congress wednesday year presid make annual determin appropri consult congress regard refuge admiss ceil follow fiscal year secretari tillerson dh act secretari duke consult congress tomorrow said',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'senat republican tax chief want dividend deduct tax reform washington reuter u senat top republican tax polici said tuesday allow u corpor deduct dividend payment sharehold feder incom tax could overcom problem face republican effort overhaul u tax code statement outset tax reform hear senat financ committe chairman orrin hatch said see propos known corpor integr way end perceiv doubl taxat u compani tax legisl would also reduc statutori u corpor incom tax rate stand percent idea whether appli fulli limit way help address number problem tri solv comprehens tax reform said hatch member big six tax polici maker trump administr congress expect issu tax reform blueprint next week',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'victim terrorist attack question lack presidenti support minnesota governor someth current occup white hous cannot quickli denounc act terror makeshift bomb tore mosqu earli saturday morn terribl dastardli cowardli terribl act commit yesterday gov mark dayton said someon said meet role revers would call terrorist attack act terror author bloomington said one injur blast citi dar al farooq islam center attack happen white evangel church morn prayer muslim donald trump would use incid promot agenda ban anyon religion enter u lash media democrat senat militari record trump still address mosqu attack unnerv muslim commun resid state still wait trump condemn attack instead amateur presid busi rage tweet critic silenc part public offici nation level serv empow islamophob ibrahim hooper spokesman council american islam relat said statement call trump condemn attack accord lo angel time wonder presid trump tweet asad zaman director muslim american societi minnesota told buzzfe news seem want tweet secur terror issu new york time white hous correspond glenn thrush tweet statement white hous monday trump still address bomb u soil email wh minn mosqu bomb presid continu updat monitor situat glenn thrush glennthrush august word compass white hous offer muslim commun terribl time fbi tweet statement fbiminneapoli updat statement special agent charg explos dar al farooq commun center pic twitter com mt jveg uc fbi minneapoli fbiminneapoli august fortun live lost physic damag repar fbi recogn pain anger commun anytim place worship attack work hard hold respons account statement read local offici condemn attack america leader seem knowledg lead go go limb suggest faith someth trump silenc matter gofundm donat page rais two day time help repair mosqu comment request donat read pleas feel welcom countri welcom sorri happen white hous may care plenti us countri wait trump address issu least pretend care want interrupt undeserv day vacat luxuri golf cours american citizen attack read photo ian macnicol getti imag',

In [60]:
print(Y)

[1 1 0 ... 0 1 0]

Converting Textual data into Numerical data

In [61]:
vectorizer=TfidfVectorizer()
vectorizer.fit(X)
X=vectorizer.transform(X)

In [62]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6904081 stored elements and shape (44898, 89868)>
  Coords	Values
  (0, 298)	0.023747845036935472
  (0, 494)	0.01685224017805291
  (0, 619)	0.020840417796011493
  (0, 821)	0.03677719969928287
  (0, 1285)	0.025450499208534795
  (0, 2217)	0.025271402861005852
  (0, 2301)	0.01275067482661736
  (0, 2562)	0.01823773546464223
  (0, 3154)	0.021371249943336477
  (0, 3186)	0.03694833028616671
  (0, 3598)	0.04937758318370229
  (0, 4617)	0.04328177276557116
  (0, 4688)	0.09886494736494873
  (0, 5357)	0.015376973250360708
  (0, 7020)	0.037273793156343375
  (0, 7298)	0.02379386174510396
  (0, 7670)	0.020536401448624265
  (0, 8254)	0.05190845888438443
  (0, 8564)	0.02795566593442498
  (0, 9031)	0.034783445091770324
  (0, 9051)	0.03738207913190706
  (0, 9445)	0.036920567083691694
  (0, 9670)	0.08722983594913031
  (0, 10418)	0.031572433862100825
  (0, 10537)	0.08207251881362854
  :	:
  (44897, 49701)	0.06290623443044062
  (44897, 53138)	0.1219543503841605
  (44897, 54902)	0.06403865759119443
  (44897, 55623)	0.050308035994027445
  (44897, 60522)	0.06526402756839617
  (44897, 61069)	0.033394026989464656
  (44897, 61235)	0.0734442660469573
  (44897, 64183)	0.09040251713593758
  (44897, 64634)	0.2435143354312243
  (44897, 65239)	0.03586547475612548
  (44897, 67558)	0.054447189523477754
  (44897, 68247)	0.12232071574306785
  (44897, 73550)	0.09707499413273518
  (44897, 73662)	0.03543727821511989
  (44897, 73678)	0.05359509561902913
  (44897, 77113)	0.2434888784536931
  (44897, 77773)	0.05910126576232697
  (44897, 77960)	0.040678463592038104
  (44897, 78442)	0.15524515112765752
  (44897, 79543)	0.06979359346634013
  (44897, 79759)	0.08256680064373208
  (44897, 81430)	0.14537597351436266
  (44897, 81621)	0.046677762825936865
  (44897, 83998)	0.217477359100759
  (44897, 86166)	0.09963691625762881

Splitting the dataset to training and test data

In [63]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=40)

Training the model

In [64]:
svm_model = LinearSVC(C=1.0, random_state=42)

svm_model.fit(X_train, Y_train)

LinearSVC(random_state=42)

In [65]:
Y_pred = svm_model.predict(X_test)

Evaluating model

In [70]:
accuracy = accuracy_score(Y_test, Y_pred)
precision = precision_score(Y_test, Y_pred, pos_label=1)
recall = recall_score(Y_test, Y_pred, pos_label=1)
f1 = f1_score(Y_test, Y_pred, pos_label=1)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print("\nClassification Report:")
print(classification_report(Y_test, Y_pred))

Accuracy : 0.994097995545657
Precision: 0.9948838200810062
Recall   : 0.993824531516184
F1 Score : 0.9943538936827527

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4284
           1       0.99      0.99      0.99      4696

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

In [75]:
#Confusion Matrix
cm = confusion_matrix(Y_test, Y_pred)
print(cm)

[[4260   24]
 [  29 4667]]

In [77]:
feature_names = np.array(vectorizer.get_feature_names_out())
coefficients = svm_model.coef_[0]

top_fake = feature_names[np.argsort(coefficients)[:20]]
top_real = feature_names[np.argsort(coefficients)[-20:][::-1]]

print("Top FAKE-related features:")
print(top_fake)

print("\nTop REAL-related features:")
print(top_real)

Top FAKE-related features:
['reuter' 'said' 'nov' 'washington' 'wednesday' 'factbox' 'thursday'
 'newspap' 'tuesday' 'rival' 'barack' 'friday' 'edt' 'km' 'urg' 'monday'
 'say' 'presidenti' 'comment' 'york']

Top REAL-related features:
['via' 'read' 'video' 'imag' 'gop' 'us' 'hillari' 'sen' 'getti' 'featur'
 'break' 'mr' 'wire' 'rep' 'com' 'america' 'entir' 'daili' 'even' 'watch']

In [78]:
decision_scores = svm_model.decision_function(X_test)

print(decision_scores[:10])

[-1.5672823   1.32844152 -0.96125561  2.33141485  0.19300485  1.28537084
  1.54567071  2.49596494  1.7977482   1.47846743]

Saving the model

In [82]:
joblib.dump(vectorizer, "D:\\TruthLens\\Model\\tfidf_vectorizer.pkl")
joblib.dump(svm_model, "D:\\TruthLens\\Model\\svm_model.pkl")

print("Model saved successfully!")

Model saved successfully!